name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    env:
      ADDITIONAL_DEBS: ros-noetic-gazebo-ros-pkgs ros-noetic-gazebo-ros-control libgazebo11-dev
      TARGET_WORKSPACE: sgm_lidar_clustering laser_scans_fusion gazebo_simulator point_cloud_assembler
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: noetic, ROS_REPO: testing}
          - {ROS_DISTRO: noetic, ROS_REPO: main}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
